MODEL:
  TYPE: samus
  NAME: SAMUS
  NUM_CLASSES: 2
  PRETRAINED: ''
  SAMUS_CHECKPOINT: '/home/wtchen/wsp/wsp_uusic/KTD/SAMUS-main/checkpoints/sam_vit_b_01ec64.pth'
  
SAMUS:
  ENCODER_INPUT_SIZE: 224
  LOW_IMAGE_SIZE: 128
  VIT_NAME: 'vit_b'
  SAM_CKPT: '/home/wtchen/wsp/wsp_uusic/KTD/SAMUS-main/checkpoints/sam_vit_b_01ec64.pth'

DATA:
  BATCH_SIZE: 4
  IMG_SIZE: 224
  DATA_PATH: 'data/'
  PIN_MEMORY: True
  NUM_WORKERS: 4

TRAIN:
  BASE_LR: 0.005
  EPOCHS: 200
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 0.01
  USE_CHECKPOINT: True
  ACCUMULATION_STEPS: 1
  CLIP_GRAD: 5.0
  
  OPTIMIZER:
    NAME: 'adamw'
    EPS: 1.0e-08
    BETAS: [0.9, 0.999]
    MOMENTUM: 0.9
    
  LR_SCHEDULER:
    NAME: 'cosine'
    DECAY_EPOCHS: 30
    DECAY_RATE: 0.1

AMP_OPT_LEVEL: 'O1'
OUTPUT: 'exp_out'
TAG: 'samus_trial'
SEED: 1234
LOCAL_RANK: 0
PRINT_FREQ: 10
SAVE_FREQ: 1